# Generated by Django 3.1.1 on 2021-04-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductImage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
