# Generated by Django 3.2 on 2021-04-16 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0003_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
    ]
