# Generated by Django 3.1.1 on 2021-04-09 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Product', '0002_auto_20210409_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('waiting', 'waiting'), ('denied', 'denied'), ('accepted', 'accepted'), ('process', 'process'), ('shipping', 'shipping'), ('shipped', 'shipped'), ('refunded', 'refunded')], max_length=30)),
                ('amount', models.FloatField()),
                ('ship_cost', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to='User.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='Product.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_order', to='User.seller')),
            ],
        ),
    ]
