# Generated by Django 3.2 on 2021-04-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_auto_20210417_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_cost',
            field=models.FloatField(null=True),
        ),
    ]
