# Generated by Django 3.1.1 on 2021-04-09 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_class',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_seller', to='User.seller'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='Sold out', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='item', max_length=30),
        ),
    ]
