# Generated by Django 3.1.1 on 2021-04-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20210409_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_like',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
