# Generated by Django 3.1.1 on 2021-04-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commentNum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='headImage',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
