# Generated by Django 3.1.1 on 2021-04-15 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20210412_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='headImage',
        ),
    ]
