# Generated by Django 3.2 on 2021-04-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_remove_product_headimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='averageRate',
            field=models.FloatField(default=0.0),
        ),
    ]
