# Generated by Django 3.1.1 on 2021-04-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210411_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('other', 'other'), ('', '')], max_length=10, null=True),
        ),
    ]
