# Generated by Django 3.1.1 on 2021-04-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20210411_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='shopCategory',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='shopName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
